name: Build Geode Mod

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        id: build
        with:
          target: ${{ matrix.config.target }}
      
      - uses: actions/upload-artifact@v7
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}
